#!/usr/bin/env bash
# This script is display
sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

trap inter2 SIGINT
trap inter1 SIGTERM
trap inter3 SIGQUIT

inter3()
{
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

inter2()
{
    echo "Y U no love me?!"
}

inter1()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
