#!/usr/bin/env bash
# This script is display
sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

trap interrup2 SIGINT
trap interrup SIGTERM
trap interrup SIGQUIT

interrup()
{
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

interrup()
{
    echo "Y U no love me?!"
}

interrup()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
