#!/usr/bin/env bash
#script that display number from 1 to 20
i=1
while [ "$i" -lt 21 ]
do
   echo "$i"
   case $i in
        4)
        echo "bad luck from china"
        ;;
        8)
        echo "bad luck from japan"
        ;;
        17)
        echo "bad luck from Italy"
        ;;
        esac
   ((i++))
done
i=$i
