#!/usr/bin/env bash
#script tht gives information
file_s="school"
if [ -e "$file_s" ]
then
  echo "school file exist"
  if [ -s "$file_s" ]
  then
    echo "school file is not empty"
  else
    echo "school file is  empty"
  fi
  if [ -f "$file_s" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
